In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import warnings
import src.workfile_functions as wf

warnings.filterwarnings('ignore')

pd.set_option('display.max_columns',50)
pd.set_option('display.max_rows',100)

PATH = '../data/pc/'

URL = "https://michael-weylandt.com/STA9890/competition_data/"

# Read in Data

In [2]:
# read in from prof's website
BUILDING_DETAILS_2015 = wf.read_gh(URL, "building_details_2015.csv.gz")
BUILDING_DETAILS_2016 = wf.read_gh(URL, "building_details_2016.csv.gz")
BUILDING_DETAILS_2017 = wf.read_gh(URL, "building_details_2017.csv.gz")
BUILDING_DETAILS_2018 = wf.read_gh(URL, "building_details_2018.csv.gz")
BUILDING_DETAILS_2019 = wf.read_gh(URL, "building_details_2019.csv.gz")

## Sample Predictions

In [3]:
TRAINING_SAMPLES = wf.read_gh(URL,"assessment_history_train.csv.gz")
TEST_POINTS = wf.read_gh(URL,"assessment_history_test.csv.gz")

KeyboardInterrupt:

In [ ]:
AVERAGE_ASSESSMENT = TRAINING_SAMPLES["TARGET"].mean()

In [ ]:
TEST_POINTS[["acct"]].rename(columns={"acct":"ACCOUNT"}).\
    assign(TARGET=AVERAGE_ASSESSMENT).\
    to_csv("../Predictions/SAMPLE_ASSESMENT.csv", index=False)

In [ ]:
TEST_POINTS["acct"]

0         bb75f25168addc1117840b10c0fd6cd0c2a7b7c6
1         8def0ccceda200b673872a8a9367644767989f3b
2         ca33e57b3b13e843909f4b6cbd9a3410387bd45a
3         3e0f6f6090a8226ce67ccf2f8630b8ad630b8d55
4         63facf82adbae10b23f7fabc93188c95bd832f51
                            ...
418853    24847d36c333ab3376848ee1bda74916286a2a4b
418854    62ba19f1655097ac9cc8682aec435d22a653bfa0
418855    552b5300d14369d8fd792ea6228dfa683014b2f5
418856    290d351d16d00e79e89dc5404412f07769f40038
418857    1c805ac0a5ac70cb82de03be002047b443f528d5
Name: acct, Length: 418858, dtype: object

In [155]:
TEST_POINTS[["acct"]].rename(columns={"acct":"ACCOUNT"}).assign(TARGET=AVERAGE_ASSESSMENT)

                                         ACCOUNT         TARGET
0       bb75f25168addc1117840b10c0fd6cd0c2a7b7c6  255304.332639
1       8def0ccceda200b673872a8a9367644767989f3b  255304.332639
2       ca33e57b3b13e843909f4b6cbd9a3410387bd45a  255304.332639
3       3e0f6f6090a8226ce67ccf2f8630b8ad630b8d55  255304.332639
4       63facf82adbae10b23f7fabc93188c95bd832f51  255304.332639
...                                          ...            ...
418853  24847d36c333ab3376848ee1bda74916286a2a4b  255304.332639
418854  62ba19f1655097ac9cc8682aec435d22a653bfa0  255304.332639
418855  552b5300d14369d8fd792ea6228dfa683014b2f5  255304.332639
418856  290d351d16d00e79e89dc5404412f07769f40038  255304.332639
418857  1c805ac0a5ac70cb82de03be002047b443f528d5  255304.332639

[418858 rows x 2 columns]

In [156]:
pd.read_csv("../Predictions/SAMPLE_ASSESMENT.csv")

                                         ACCOUNT         TARGET
0       bb75f25168addc1117840b10c0fd6cd0c2a7b7c6  255304.332639
1       8def0ccceda200b673872a8a9367644767989f3b  255304.332639
2       ca33e57b3b13e843909f4b6cbd9a3410387bd45a  255304.332639
3       3e0f6f6090a8226ce67ccf2f8630b8ad630b8d55  255304.332639
4       63facf82adbae10b23f7fabc93188c95bd832f51  255304.332639
...                                          ...            ...
418853  24847d36c333ab3376848ee1bda74916286a2a4b  255304.332639
418854  62ba19f1655097ac9cc8682aec435d22a653bfa0  255304.332639
418855  552b5300d14369d8fd792ea6228dfa683014b2f5  255304.332639
418856  290d351d16d00e79e89dc5404412f07769f40038  255304.332639
418857  1c805ac0a5ac70cb82de03be002047b443f528d5  255304.332639

[418858 rows x 2 columns]

# Initial data look

In [157]:
TRAINING_SAMPLES

,acct,building_area_2015,land_area_2015,building_area_2016,land_area_2016,building_area_2017,land_area_2017,building_area_2018,land_area_2018,region,building_area_2019,land_area_2019,building_value_2015,land_value_2015,building_value_2016,land_value_2016,building_value_2017,land_value_2017,building_value_2018,land_value_2018,building_value_2019,land_value_2019,assessed_2015,protested_2015,assessed_2016,protested_2016,assessed_2017,protested_2017,assessed_2018,protested_2018,assessed_2019,protested_2019,school_dist,zone,subneighborhood,neighborhood,TARGET
0,cb6434705a05b139cb63994aa2a194b226b9e750,1853.0,4263.0,1853.0,4263.0,1853.0,4263.0,1853.0,4263.0,05946c0909f5c241db6179659dc763e14544cf75,1853,4263,80939.0,22061.0,80939.0,22061.0,97988.0,24512.0,97988.0,24512.0,120488,24512,103000.0,True,103000.0,True,122500.0,True,122500.0,True,145000,True,8.0,1b2fc12a8ee5147b030dae24f76bfb63bf401fdd,9bd56df07606b41647719f2022859ef0571cf82c,78bde8025e65c00938c9f5a63f652c33c7b7fc61,145000
1,965bbe53f6f63e4853b5a30ba28cf016d489de80,1282.0,6780.0,1282.0,6780.0,1282.0,6780.0,1282.0,6780.0,7fb552ebc782591a0e4a0b770897f05ddc782d7d,1282,6780,74056.0,13526.0,74308.0,13526.0,78545.0,13526.0,78545.0,13526.0,70374,12580,92171.0,False,92171.0,False,92171.0,False,92171.0,False,87291,False,9.0,34827051b895693d5256b50bbfd93d1edfcc9e57,25f65e19a463ff57232c7dfcde28e5da1e1daf2e,5495e69e361f526f9e9cd261fa962d6855a25e1d,87291
2,c68f351c68aa385ec1e8c866e5f8f27486894ca1,1705.0,11400.0,1705.0,11400.0,1705.0,11400.0,1705.0,11400.0,6bbed0508643ceb1fc53fd0d87d5bd5692e63f59,1705,11400,49042.0,11325.0,53543.0,11325.0,77254.0,11325.0,77254.0,11325.0,77390,11325,64968.0,False,64968.0,False,93038.0,False,93038.0,False,93038,False,1.0,08900a31f38af1b7cc90edbf7fe0a51b223b7cea,b7a148094f9e45c93317ecd470468158badfdd67,95b716d0ecd06b5817ac70061b3891e9b2b1b9df,93038
3,dcd1fedd707398670790d4e2dc2f3959755644bc,1525.0,6050.0,1525.0,6050.0,1525.0,6050.0,1525.0,6050.0,05946c0909f5c241db6179659dc763e14544cf75,1525,6050,85632.0,21368.0,116825.0,25988.0,132614.0,25988.0,128475.0,25988.0,127337,25988,107000.0,True,142813.0,False,158602.0,False,154463.0,True,153325,True,8.0,80d118e9664f13333ec56471233757aae3670248,3e4238a9dede4db257f8db619ba3ae59dae8c22b,2cf01a6f31e9209edc33e04502c3ac792ccfe483,153325
4,e6945b0343e266eb516cbd035093aa8f111cf21f,2873.0,12371.0,2873.0,12371.0,2873.0,12371.0,2873.0,12371.0,8313aed7a2170658379a4543432d30a7a4c9c0f9,2873,12371,141722.0,23175.0,141722.0,23175.0,141722.0,23175.0,141722.0,23175.0,166403,23175,167732.0,False,167732.0,False,167732.0,False,167732.0,False,192413,False,24.0,01607e23a50f715d7b6156391072890485810e80,2230753ca14dfdaf45cadf8b44b39d64868395f2,dec42cf689b88bc6c3376b744ba1eef6241bb72e,192413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628282,096ae9cd01609cb0893f2ef91dc757824e4e84f2,1244.0,6100.0,1244.0,6100.0,1244.0,6100.0,1290.0,6100.0,53b44e3ba0274a953f00c6a4f243af6fd657441c,1290,6100,26431.0,21155.0,25845.0,21155.0,35826.0,21155.0,40504.0,21155.0,57685,21155,47586.0,True,47000.0,True,61759.0,True,61759.0,False,83618,False,1.0,150b0c90f6f18276a82812c2a6bed3bbe9add993,24ce4a223839d38455a71f576d14816c4f96a925,f97870b520c0b80d6f964e57f66bfea7217b703c,83618
628283,0b477a421bd606cc68cd53bc094e074870bdb335,3258.0,12462.0,3258.0,12462.0,3258.0,12462.0,3258.0,12462.0,73272a9db0603a7068160caeb15afed2820bbadf,3258,12462,227466.0,40949.0,236165.0,40949.0,240128.0,40949.0,243905.0,40949.0,228082,40949,288331.0,False,295441.0,False,295441.0,False,295441.0,False,288938,False,4.0,5a79ad5a4cc243ac735c2d2c9cc04ad3f3fda9f1,a3f18e57e2fdaa8bf459624c22f37bacd103bc2c,30577f438c93eacf7447a0c96d3a7368f456d31e,288938
628284,c09bb8493d33797362fd894c49cf7d4e02509a8a,1019.0,6350.0,1019.0,6350.0,1129.0,6350.0,1129.0,6350.0,69186afde5778b2d53c6f0290a77b2ae7e7eacf8,1129,6350,24544.0,18105.0,27331.0,18105.0,30408.0,18105.0,31032.0,18105.0,35987,21123,43086.0,False,45873.0,False,50367.0,False,50367.0,False,58964,False,21.0,7a3a110de410d0375488c17e76b9852b9d561bb1,1030c1552a14200c0172046f4670999d56042206,7fabaf66ab7562c1756cf1b578b6b17f2a9c6755,58964
628285,2e4ed275ab26ed4aefc2e80bc1db5b5cb7cae88a,1587.0,8120.0,1587.0,8120.0,1587.0,8120.0,1587.0,8120.0,5896273aea65a613927863b34d36fbd4df8db94b,1587,8120,59885.0,26240.0,86145.0,36080.0,90624.0,38376.0,90524.0,38376.0,116990,45920,86125.0,True,122225.0,True,129000.0,True,129000.0,False,164477,False,1.0,2c8f23877d67497e8d1605586171a421df6558e9,fa60614f0853bfff1aa9b88a81ed16f069cacd46,e68c339cd98d4f33a58d2c162ce4db94a3f1f19e,164477
628286,5eccd04f798d31921aa33d411b838a99148619d0,1124.0,3825.0,1124.0,3825.0,1124.0,3825.0,1124.0,3825.0,2cb79e74518975e7b4c38b06a58a126ec8045935,1124,3825,67480.0,13409.0,72259.0,13409.0,82568.0,13409.0,82568.0,13409.0,93828,13409,80889.0,False,85668.0,False,95977.0,False,95977.0,False,107237,False,24.0,424bf4599f0c294992164d5415fc40a64c86e910,78fbcc5465706dc5110c472204a034b60df5c9f1,02ade0a5d89a6545c4e78c368dfa0d7e967c26f4,107237

In [158]:
BUILDING_DETAILS_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990765 entries, 0 to 990764
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   acct                 990765 non-null  object
 1   floor_area_primary   990764 non-null  float64
 2   floor_area_upper     990764 non-null  float64
 3   floor_area_lower     990764 non-null  float64
 4   garage_area          990764 non-null  float64
 5   porch_area           990764 non-null  float64
 6   deck_area            990764 non-null  float64
 7   mobile_home_area     990764 non-null  float64
 8   floors               990763 non-null  float64
 9   half_bath            990763 non-null  float64
 10  full_bath            990763 non-null  float64
 11  total_rooms          990763 non-null  float64
 12  bedrooms             990763 non-null  float64
 13  fireplaces           990763 non-null  float64
 14  elevator             990763 non-null  object
 15  quality              987070 non-null  object
 16  quality_description  987070 non-null  object
 17  year_built           987070 non-null  float64
 18  year_remodeled       987070 non-null  float64
 19  building_condition   988868 non-null  object
 20  foundation_type      988867 non-null  object
 21  grade                988870 non-null  object
 22  has_cooling          988868 non-null  object
 23  has_heat             988868 non-null  object
 24  physical_condition   988866 non-null  object
 25  exterior_walls       988868 non-null  object
 26  year                 988871 non-null  float64
dtypes: float64(16), object(11)
memory usage: 204.1+ MB

In [159]:
df = BUILDING_DETAILS_2015.copy(deep=True)

In [160]:
wf.count_nulls(df)

Column                              NULL Count    % of Rows
------------------------------------------------------------
quality                                  3,695        0.37%
quality_description                      3,695        0.37%
year_built                               3,695        0.37%
year_remodeled                           3,695        0.37%
physical_condition                       1,899        0.19%
foundation_type                          1,898        0.19%
building_condition                       1,897        0.19%
has_cooling                              1,897        0.19%
has_heat                                 1,897        0.19%
exterior_walls                           1,897        0.19%
grade                                    1,895        0.19%
year                                     1,894        0.19%
floors                                       2        0.00%
half_bath                                    2        0.00%
full_bath                                    2        0.00%
total_rooms                                  2        0.00%
bedrooms                                     2        0.00%
fireplaces                                   2        0.00%
elevator                                     2        0.00%
floor_area_primary                           1        0.00%
floor_area_upper                             1        0.00%
floor_area_lower                             1        0.00%
garage_area                                  1        0.00%
porch_area                                   1        0.00%
deck_area                                    1        0.00%
mobile_home_area                             1        0.00%

In [161]:
df.head(3)

,acct,floor_area_primary,floor_area_upper,floor_area_lower,garage_area,porch_area,deck_area,mobile_home_area,floors,half_bath,full_bath,total_rooms,bedrooms,fireplaces,elevator,quality,quality_description,year_built,year_remodeled,building_condition,foundation_type,grade,has_cooling,has_heat,physical_condition,exterior_walls,year
0,bb75f25168addc1117840b10c0fd6cd0c2a7b7c6,1658.0,879.0,0.0,0.0,266.0,0.0,0.0,2.0,1.0,2.0,8.0,3.0,0.0,False,B,Good,2004.0,0.0,Fair,Slab,B-,True,True,Fair,Stucco,2015.0
1,5dd766a35cebbcbfa063316adb679131dbb9f92c,912.0,0.0,0.0,0.0,48.0,0.0,0.0,2.0,0.0,2.0,6.0,3.0,0.0,False,D,Low,1949.0,0.0,Fair,Crawl Space,D-,False,False,Fair,Concrete Block,2015.0
2,8def0ccceda200b673872a8a9367644767989f3b,1496.0,0.0,0.0,0.0,182.0,0.0,0.0,1.0,0.0,1.0,6.0,3.0,0.0,False,D,Low,1917.0,0.0,Poor,Crawl Space,D,False,False,Poor,Concrete Block,2015.0

## Imputing Categorical Data

In [162]:
non_numeric = wf.get_columns_by_dtype(df,dtypes=['object'])
non_numeric

['acct',
 'elevator',
 'quality',
 'quality_description',
 'building_condition',
 'foundation_type',
 'grade',
 'has_cooling',
 'has_heat',
 'physical_condition',
 'exterior_walls']

In [163]:
df[non_numeric]

,acct,elevator,quality,quality_description,building_condition,foundation_type,grade,has_cooling,has_heat,physical_condition,exterior_walls
0,bb75f25168addc1117840b10c0fd6cd0c2a7b7c6,False,B,Good,Fair,Slab,B-,True,True,Fair,Stucco
1,5dd766a35cebbcbfa063316adb679131dbb9f92c,False,D,Low,Fair,Crawl Space,D-,False,False,Fair,Concrete Block
2,8def0ccceda200b673872a8a9367644767989f3b,False,D,Low,Poor,Crawl Space,D,False,False,Poor,Concrete Block
3,7592093bcff4a8463064ccc1ead39e6dbdb819c9,False,B,Good,Average,Slab,B,True,True,Average,Brick Veneer and Concrete Block
4,ca33e57b3b13e843909f4b6cbd9a3410387bd45a,False,C,Average,Fair,Slab,C,True,True,Average,Brick Masonry and Concrete Block
...,...,...,...,...,...,...,...,...,...,...,...
990760,2f9fbea48883c2f530f384e5bc69a9268e6de643,False,C,Average,Average,Slab,C,True,True,Average,Brick Masonry and Concrete Block
990761,f4754d6d14db17406de498e110a08893241305d6,False,C,Average,Average,Slab,C,True,True,Average,Brick Veneer
990762,0b85ebef5f4d83efb420ae780c2c8d82d0574771,False,C,Average,Average,Slab,C,True,True,Average,Brick Veneer
990763,c0fc5ae680322e79c8e80abeb4015319fa0c9de6,False,C,Average,Average,Slab,C,True,True,Average,Brick Masonry and Concrete Block
990764,3db28413f364c8863957f222d3822cdae477ddeb,False,C,Average,Average,Crawl Space,C-,False,False,Average,Vinyl

### True/False Cols

In [164]:
tfcols = ['elevator','has_cooling','has_heat']

In [165]:
# test = df.copy(deep=True)

In [166]:
df[tfcols]

       elevator has_cooling has_heat
0         False        True     True
1         False       False    False
2         False       False    False
3         False        True     True
4         False        True     True
...         ...         ...      ...
990760    False        True     True
990761    False        True     True
990762    False        True     True
990763    False        True     True
990764    False       False    False

[990765 rows x 3 columns]

In [167]:
df['elevator'].value_counts(dropna=False)

elevator
False    988010
True       2753
NaN           2
Name: count, dtype: int64

In [168]:
for col in tfcols:
    df[col] = df[col].astype('Int64')

In [169]:
df[tfcols]

        elevator  has_cooling  has_heat
0              0            1         1
1              0            0         0
2              0            0         0
3              0            1         1
4              0            1         1
...          ...          ...       ...
990760         0            1         1
990761         0            1         1
990762         0            1         1
990763         0            1         1
990764         0            0         0

[990765 rows x 3 columns]

In [170]:
df['elevator'].value_counts(dropna=False)

elevator
0       988010
1         2753
<NA>         2
Name: count, dtype: Int64

### Non-Numeric Ordinal Columns

In [171]:
ord = ['quality','quality_description','building_condition','grade','physical_condition']
non_ord = ['foundation_type','exterior_walls']

In [172]:
df[ord]

       quality quality_description building_condition grade physical_condition
0            B                Good               Fair    B-               Fair
1            D                 Low               Fair    D-               Fair
2            D                 Low               Poor     D               Poor
3            B                Good            Average     B            Average
4            C             Average               Fair     C            Average
...        ...                 ...                ...   ...                ...
990760       C             Average            Average     C            Average
990761       C             Average            Average     C            Average
990762       C             Average            Average     C            Average
990763       C             Average            Average     C            Average
990764       C             Average            Average    C-            Average

[990765 rows x 5 columns]

In [173]:
# checking the quality column
df['quality'].value_counts(dropna=False)

quality
C      616472
B      223831
D       80286
A       54024
X        8705
E        3739
NaN      3695
F          13
Name: count, dtype: int64

In [174]:
# This data is pretty ordinal in nature
quality_map = {
    'F':0,
    'E':1,
    'D':2,
    'C':3,
    'B':4,
    'A':5,
    'X':6
}

df['quality'] = df['quality'].map(quality_map)

In [175]:
df['quality'].value_counts(dropna=False)

quality
3.0    616472
4.0    223831
2.0     80286
5.0     54024
6.0      8705
1.0      3739
NaN      3695
0.0        13
Name: count, dtype: int64

In [176]:
df['quality_description'].value_counts(dropna=False)

quality_description
Average      616472
Good         223831
Low           80286
Excellent     54024
Superior       8705
Very Low       3739
NaN            3695
Poor             13
Name: count, dtype: int64

In [177]:
quality_description_map = {
    'Poor':0,
    'Very Low':1,
    'Low':2,
    'Average':3,
    'Good':4,
    'Excellent':5,
    'Superior':6
}

df['quality_description'] = df['quality_description'].map(quality_description_map)

In [178]:
df['quality_description'].value_counts(dropna=False)

quality_description
3.0    616472
4.0    223831
2.0     80286
5.0     54024
6.0      8705
1.0      3739
NaN      3695
0.0        13
Name: count, dtype: int64

In [179]:
df['building_condition'].value_counts()

building_condition
Average      674307
Good         142695
Fair          96446
Very Good     41161
Poor          21235
Very Poor      5981
Excellent      5943
Unsound        1100
Name: count, dtype: int64

In [180]:
bc_map ={
    'Unsound':0,
    'Very Poor':1,
    'Poor':2,
    'Fair':3,
    'Average':4,
    'Good':5,
    'Very Good':6,
    'Excellent':7
}

df['building_condition'] = df['building_condition'].map(bc_map)

In [181]:
df['building_condition'].value_counts(dropna=False)

building_condition
4.0    674307
5.0    142695
3.0     96446
6.0     41161
2.0     21235
1.0      5981
7.0      5943
NaN      1897
0.0      1100
Name: count, dtype: int64

In [182]:
df['grade'].value_counts(dropna=False)

grade
C      342099
C+     200720
B-      94558
B       82475
C-      72292
B+      50753
D       40019
D+      28237
A-      21129
A       18547
A+      14099
D-      11387
X-       5260
X        2952
E        2011
NaN      1895
E+       1354
X+        736
E-        242
Name: count, dtype: int64

In [183]:
grade_map = {
    'E-':1.3,
    'E':1.6,
    'E+':1.9,
    'D-':2.3,
    'D':2.6,
    'D+':2.9,
    'C-':3.3,
    'C':3.6,
    'C+':3.9,
    'B-':4.3,
    'B':4.6,
    'B+':4.9,
    'A-':5.3,
    'A':5.6,
    'A+':5.9,
    'X-':6.3,
    'X':6.6,
    'X+':6.9
}

df['grade'] = df['grade'].map(grade_map)

In [184]:
df['grade'].value_counts()

grade
3.6    342099
3.9    200720
4.3     94558
4.6     82475
3.3     72292
4.9     50753
2.6     40019
2.9     28237
5.3     21129
5.6     18547
5.9     14099
2.3     11387
6.3      5260
6.6      2952
1.6      2011
1.9      1354
6.9       736
1.3       242
Name: count, dtype: int64

In [185]:
df['physical_condition'].value_counts()

physical_condition
Average      820109
Good          83041
Fair          50898
Very Good     14451
Poor          11911
Excellent      5821
Very Poor      1711
Unsound         924
Name: count, dtype: int64

In [186]:
pc_map = {
    'Unsound':0,
    'Very Poor':1,
    'Poor':2,
    'Fair':3,
    'Average':4,
    'Good':5,
    'Very Good':6,
    'Excellent':7
}

df['physical_condition'] = df['physical_condition'].map(pc_map)

In [187]:
df['physical_condition'].value_counts(dropna=False)

physical_condition
4.0    820109
5.0     83041
3.0     50898
6.0     14451
2.0     11911
7.0      5821
NaN      1899
1.0      1711
0.0       924
Name: count, dtype: int64

In [188]:
df[ord]

,quality,quality_description,building_condition,grade,physical_condition
0,4.0,4.0,3.0,4.3,3.0
1,2.0,2.0,3.0,2.3,3.0
2,2.0,2.0,2.0,2.6,2.0
3,4.0,4.0,4.0,4.6,4.0
4,3.0,3.0,3.0,3.6,4.0
...,...,...,...,...,...
990760,3.0,3.0,4.0,3.6,4.0
990761,3.0,3.0,4.0,3.6,4.0
990762,3.0,3.0,4.0,3.6,4.0
990763,3.0,3.0,4.0,3.6,4.0
990764,3.0,3.0,4.0,3.3,4.0

### Non-Numeric Non-Ordinal

In [189]:
df[non_ord]

       foundation_type                    exterior_walls
0                 Slab                            Stucco
1          Crawl Space                    Concrete Block
2          Crawl Space                    Concrete Block
3                 Slab   Brick Veneer and Concrete Block
4                 Slab  Brick Masonry and Concrete Block
...                ...                               ...
990760            Slab  Brick Masonry and Concrete Block
990761            Slab                      Brick Veneer
990762            Slab                      Brick Veneer
990763            Slab  Brick Masonry and Concrete Block
990764     Crawl Space                             Vinyl

[990765 rows x 2 columns]

In [190]:
# Start with foundation type
df['foundation_type'].value_counts(dropna=False)

foundation_type
Slab                     886063
Crawl Space              100998
NaN                        1898
Basement                   1718
Crawl Space and Slab         81
Basement and Basement         5
Basement and Slab             2
Name: count, dtype: int64

In [191]:
df.loc[df['foundation_type'] == 'Basement and Basement', 'foundation_type'] = 'Basement'

In [192]:
# Start with foundation type
df['foundation_type'].value_counts(dropna=False)

foundation_type
Slab                    886063
Crawl Space             100998
NaN                       1898
Basement                  1723
Crawl Space and Slab        81
Basement and Slab            2
Name: count, dtype: int64

In [193]:
df.loc[(df['foundation_type']=='Basement and Slab')|(df['foundation_type']=='Crawl Space and Slab'),'foundation_type'] = 'Mixed'

In [194]:
df['foundation_type'].value_counts(dropna=False)

foundation_type
Slab           886063
Crawl Space    100998
NaN              1898
Basement         1723
Mixed              83
Name: count, dtype: int64

In [195]:
dummies = pd.get_dummies(df['foundation_type'], prefix='foundation').astype('Int64')
df = pd.concat([df, dummies], axis=1)

In [196]:
df

,acct,floor_area_primary,floor_area_upper,floor_area_lower,garage_area,porch_area,deck_area,mobile_home_area,floors,half_bath,full_bath,total_rooms,bedrooms,fireplaces,elevator,quality,quality_description,year_built,year_remodeled,building_condition,foundation_type,grade,has_cooling,has_heat,physical_condition,exterior_walls,year,foundation_Basement,foundation_Crawl Space,foundation_Mixed,foundation_Slab
0,bb75f25168addc1117840b10c0fd6cd0c2a7b7c6,1658.0,879.0,0.0,0.0,266.0,0.0,0.0,2.0,1.0,2.0,8.0,3.0,0.0,0,4.0,4.0,2004.0,0.0,3.0,Slab,4.3,1,1,3.0,Stucco,2015.0,0,0,0,1
1,5dd766a35cebbcbfa063316adb679131dbb9f92c,912.0,0.0,0.0,0.0,48.0,0.0,0.0,2.0,0.0,2.0,6.0,3.0,0.0,0,2.0,2.0,1949.0,0.0,3.0,Crawl Space,2.3,0,0,3.0,Concrete Block,2015.0,0,1,0,0
2,8def0ccceda200b673872a8a9367644767989f3b,1496.0,0.0,0.0,0.0,182.0,0.0,0.0,1.0,0.0,1.0,6.0,3.0,0.0,0,2.0,2.0,1917.0,0.0,2.0,Crawl Space,2.6,0,0,2.0,Concrete Block,2015.0,0,1,0,0
3,7592093bcff4a8463064ccc1ead39e6dbdb819c9,1517.0,1870.0,0.0,529.0,174.0,0.0,0.0,2.0,1.0,3.0,6.0,3.0,0.0,0,4.0,4.0,2015.0,0.0,4.0,Slab,4.6,1,1,4.0,Brick Veneer and Concrete Block,2015.0,0,0,0,1
4,ca33e57b3b13e843909f4b6cbd9a3410387bd45a,1508.0,0.0,0.0,420.0,0.0,0.0,0.0,1.0,0.0,2.0,5.0,3.0,1.0,0,3.0,3.0,2003.0,0.0,3.0,Slab,3.6,1,1,4.0,Brick Masonry and Concrete Block,2015.0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990760,2f9fbea48883c2f530f384e5bc69a9268e6de643,1611.0,0.0,0.0,400.0,35.0,0.0,0.0,1.0,0.0,2.0,6.0,3.0,0.0,0,3.0,3.0,2003.0,0.0,4.0,Slab,3.6,1,1,4.0,Brick Masonry and Concrete Block,2015.0,0,0,0,1
990761,f4754d6d14db17406de498e110a08893241305d6,2168.0,0.0,0.0,484.0,48.0,0.0,0.0,1.0,0.0,2.0,5.0,3.0,1.0,0,3.0,3.0,1979.0,0.0,4.0,Slab,3.6,1,1,4.0,Brick Veneer,2015.0,0,0,0,1
990762,0b85ebef5f4d83efb420ae780c2c8d82d0574771,1723.0,0.0,0.0,460.0,76.0,0.0,0.0,1.0,0.0,2.0,6.0,3.0,1.0,0,3.0,3.0,1983.0,0.0,4.0,Slab,3.6,1,1,4.0,Brick Veneer,2015.0,0,0,0,1
990763,c0fc5ae680322e79c8e80abeb4015319fa0c9de6,576.0,576.0,0.0,486.0,0.0,0.0,0.0,2.0,1.0,2.0,5.0,3.0,1.0,0,3.0,3.0,1979.0,0.0,4.0,Slab,3.6,1,1,4.0,Brick Masonry and Concrete Block,2015.0,0,0,0,1
990764,3db28413f364c8863957f222d3822cdae477ddeb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,4.0,2.0,0.0,0,3.0,3.0,1935.0,0.0,4.0,Crawl Space,3.3,0,0,4.0,Vinyl,2015.0,0,1,0,0

In [197]:
# exterior walls
df['exterior_walls'].value_counts(dropna=False)

exterior_walls
Brick Veneer                                                    377135
Brick Masonry and Concrete Block                                202570
Brick Veneer and Concrete Block                                 134428
Concrete Block                                                  120632
Other                                                            39437
Vinyl                                                            38414
Stucco                                                           24592
Brick Veneer and Concrete Block and Stone                        13098
Brick Veneer and Stone                                            6932
Concrete Block and Stucco                                         6088
Stone and Stucco                                                  4609
Concrete Block and Stone                                          3235
Brick Veneer and Stucco                                           2742
Brick Masonry                                                     2538
NaN                                                               1897
Brick Veneer and Vinyl                                            1645
Brick Veneer and Other                                            1602
Stone                                                             1206
Concrete Block and Stone and Stucco                               1156
Brick Veneer and Concrete Block and Stucco                         974
Brick Veneer and Stone and Stucco                                  936
Concrete Block and Other                                           612
Brick Masonry and Vinyl                                            553
Brick Masonry and Concrete Block and Stone                         542
Brick Veneer and Concrete Block and Stone and Stucco               430
Brick Masonry and Stucco                                           406
Brick Veneer and Concrete Block and Other                          364
Brick Masonry and Stone                                            347
Concrete Block and Vinyl                                           304
Stone and Vinyl                                                    198
Brick Masonry and Concrete Block and Stucco                        164
Brick Masonry and Other                                            148
Stucco and Vinyl                                                   118
Other and Stone                                                    110
Brick Veneer and Concrete Block and Other and Stone                 71
Other and Vinyl                                                     56
Concrete Block and Other and Stone                                  49
Brick Masonry and Stone and Stucco                                  47
Brick Masonry and Brick Veneer                                      46
Brick Veneer and Concrete Block and Vinyl                           42
Other and Stucco                                                    35
Concrete Block and Stucco and Vinyl                                 29
Brick Veneer and Other and Stone                                    28
Brick Masonry and Concrete Block and Other and Stone                25
Brick Masonry and Brick Veneer and Concrete Block                   23
Brick Masonry and Brick Veneer and Concrete Block and Stucco        21
Brick Veneer and Other and Vinyl                                    20
Brick Masonry and Concrete Block and Stone and Stucco               15
Brick Masonry and Concrete Block and Other                          14
Brick Masonry and Concrete Block and Vinyl                          13
Concrete Block and Stone and Vinyl                                  11
Brick Veneer and Stone and Vinyl                                    10
Brick Veneer and Stucco and Vinyl                                    9
Brick Veneer and Other and Stucco                                    6
Other and Stone and Stucco                                           5
Concrete Block and Other and Vinyl                                   4
Brick Masonry and Brick Veneer and Stone                             4
Brick Masonry and Other and Stone                                    3
Concrete Block and Stone and Stucco and Vinyl                        2
Brick Veneer and Concrete Block and Other and Vinyl                  2
Brick Masonry and Concrete Block and Other and Stucco                2
Brick Veneer and Concrete Block and Stone and Vinyl                  2
Brick Veneer and Concrete Block and Stucco and Vinyl                 1
Brick Masonry and Brick Veneer and Stucco                            1
Brick Masonry and Stucco and Vinyl                                   1
Stone and Stucco and Vinyl                                           1
Other and Stone and Vinyl                                            1
Brick Masonry and Other and Vinyl                                    1
Brick Veneer and Concrete Block and Other and Stucco                 1
Concrete Block and Other and Stucco                                  1
Brick Masonry and Other and Stucco                                   1
Name: count, dtype: int64

In [198]:
df = wf.group_rare_categories(df, 'exterior_walls', threshold=1000, new_label='Other')

In [199]:
df['exterior_walls'].value_counts(dropna=False)

exterior_walls
Brick Veneer                                 377135
Brick Masonry and Concrete Block             202570
Brick Veneer and Concrete Block              134428
Concrete Block                               120632
Other                                         46246
Vinyl                                         38414
Stucco                                        24592
Brick Veneer and Concrete Block and Stone     13098
Brick Veneer and Stone                         6932
Concrete Block and Stucco                      6088
Stone and Stucco                               4609
Concrete Block and Stone                       3235
Brick Veneer and Stucco                        2742
Brick Masonry                                  2538
NaN                                            1897
Brick Veneer and Vinyl                         1645
Brick Veneer and Other                         1602
Stone                                          1206
Concrete Block and Stone and Stucco            1156
Name: count, dtype: int64

In [200]:
# Keywords to extract
keywords = [
    'Brick Veneer',
    'Brick Masonry',
    'Concrete Block',
    'Vinyl',
    'Stucco',
    'Stone',
    'Other'
]

# Create 1/0 dummy columns based on substring presence
for key in keywords:
    col_name = key.replace(' ', '_').lower()  # e.g., 'Brick Veneer' → 'brick_veneer'
    df[col_name] = df['exterior_walls'].fillna('').str.contains(key).astype('int8')

In [204]:
df.drop(['foundation_type','exterior_walls'],axis=1,inplace=True)

In [205]:
df.head(3)

,acct,floor_area_primary,floor_area_upper,floor_area_lower,garage_area,porch_area,deck_area,mobile_home_area,floors,half_bath,full_bath,total_rooms,bedrooms,fireplaces,elevator,quality,quality_description,year_built,year_remodeled,building_condition,grade,has_cooling,has_heat,physical_condition,year,foundation_Basement,foundation_Crawl Space,foundation_Mixed,foundation_Slab,brick_veneer,brick_masonry,concrete_block,vinyl,stucco,stone,other
0,bb75f25168addc1117840b10c0fd6cd0c2a7b7c6,1658.0,879.0,0.0,0.0,266.0,0.0,0.0,2.0,1.0,2.0,8.0,3.0,0.0,0,4.0,4.0,2004.0,0.0,3.0,4.3,1,1,3.0,2015.0,0,0,0,1,0,0,0,0,1,0,0
1,5dd766a35cebbcbfa063316adb679131dbb9f92c,912.0,0.0,0.0,0.0,48.0,0.0,0.0,2.0,0.0,2.0,6.0,3.0,0.0,0,2.0,2.0,1949.0,0.0,3.0,2.3,0,0,3.0,2015.0,0,1,0,0,0,0,1,0,0,0,0
2,8def0ccceda200b673872a8a9367644767989f3b,1496.0,0.0,0.0,0.0,182.0,0.0,0.0,1.0,0.0,1.0,6.0,3.0,0.0,0,2.0,2.0,1917.0,0.0,2.0,2.6,0,0,2.0,2015.0,0,1,0,0,0,0,1,0,0,0,0

# Data Cleaning Pipeline

Now that we know how we'd like to clean these files, we can turn it into a function.

In [207]:
def clean_df(df):
    tfcols = ['elevator','has_cooling','has_heat']
    for col in tfcols:
        df[col] = df[col].astype('Int64')

    quality_map = {
    'F':0,
    'E':1,
    'D':2,
    'C':3,
    'B':4,
    'A':5,
    'X':6
    }

    df['quality'] = df['quality'].map(quality_map)

    quality_description_map = {
        'Poor':0,
        'Very Low':1,
        'Low':2,
        'Average':3,
        'Good':4,
        'Excellent':5,
        'Superior':6
    }

    df['quality_description'] = df['quality_description'].map(quality_description_map)

    bc_map = {
        'Unsound':0,
        'Very Poor':1,
        'Poor':2,
        'Fair':3,
        'Average':4,
        'Good':5,
        'Very Good':6,
        'Excellent':7
    }

    df['building_condition'] = df['building_condition'].map(bc_map)

    grade_map = {
        'E-':1.3,
        'E':1.6,
        'E+':1.9,
        'D-':2.3,
        'D':2.6,
        'D+':2.9,
        'C-':3.3,
        'C':3.6,
        'C+':3.9,
        'B-':4.3,
        'B':4.6,
        'B+':4.9,
        'A-':5.3,
        'A':5.6,
        'A+':5.9,
        'X-':6.3,
        'X':6.6,
        'X+':6.9
    }

    df['grade'] = df['grade'].map(grade_map)

    pc_map = {
        'Unsound':0,
        'Very Poor':1,
        'Poor':2,
        'Fair':3,
        'Average':4,
        'Good':5,
        'Very Good':6,
        'Excellent':7
    }

    df['physical_condition'] = df['physical_condition'].map(pc_map)

    df.loc[df['foundation_type'] == 'Basement and Basement', 'foundation_type'] = 'Basement'

    df.loc[(df['foundation_type']=='Basement and Slab')|(df['foundation_type']=='Crawl Space and Slab'),'foundation_type'] = 'Mixed'

    dummies = pd.get_dummies(df['foundation_type'], prefix='foundation').astype('Int64')
    df = pd.concat([df, dummies], axis=1)
        
    df = wf.group_rare_categories(df, 'exterior_walls', threshold=1000, new_label='Other')

    # Keywords to extract
    keywords = [
        'Brick Veneer',
        'Brick Masonry',
        'Concrete Block',
        'Vinyl',
        'Stucco',
        'Stone',
        'Other'
    ]

    # Create 1/0 dummy columns based on substring presence
    for key in keywords:
        col_name = key.replace(' ', '_').lower()  # e.g., 'Brick Veneer' → 'brick_veneer'
        df[col_name] = df['exterior_walls'].fillna('').str.contains(key).astype('int8')

    df = df.drop(['exterior_walls','foundation_type'],axis=1)

    return df

In [209]:
test = BUILDING_DETAILS_2015.copy(deep=True)

In [210]:
test = clean_df(test)

In [211]:
test

,acct,floor_area_primary,floor_area_upper,floor_area_lower,garage_area,porch_area,deck_area,mobile_home_area,floors,half_bath,full_bath,total_rooms,bedrooms,fireplaces,elevator,quality,quality_description,year_built,year_remodeled,building_condition,grade,has_cooling,has_heat,physical_condition,year,foundation_Basement,foundation_Crawl Space,foundation_Mixed,foundation_Slab,brick_veneer,brick_masonry,concrete_block,vinyl,stucco,stone,other
0,bb75f25168addc1117840b10c0fd6cd0c2a7b7c6,1658.0,879.0,0.0,0.0,266.0,0.0,0.0,2.0,1.0,2.0,8.0,3.0,0.0,0,4.0,4.0,2004.0,0.0,3.0,4.3,1,1,3.0,2015.0,0,0,0,1,0,0,0,0,1,0,0
1,5dd766a35cebbcbfa063316adb679131dbb9f92c,912.0,0.0,0.0,0.0,48.0,0.0,0.0,2.0,0.0,2.0,6.0,3.0,0.0,0,2.0,2.0,1949.0,0.0,3.0,2.3,0,0,3.0,2015.0,0,1,0,0,0,0,1,0,0,0,0
2,8def0ccceda200b673872a8a9367644767989f3b,1496.0,0.0,0.0,0.0,182.0,0.0,0.0,1.0,0.0,1.0,6.0,3.0,0.0,0,2.0,2.0,1917.0,0.0,2.0,2.6,0,0,2.0,2015.0,0,1,0,0,0,0,1,0,0,0,0
3,7592093bcff4a8463064ccc1ead39e6dbdb819c9,1517.0,1870.0,0.0,529.0,174.0,0.0,0.0,2.0,1.0,3.0,6.0,3.0,0.0,0,4.0,4.0,2015.0,0.0,4.0,4.6,1,1,4.0,2015.0,0,0,0,1,1,0,1,0,0,0,0
4,ca33e57b3b13e843909f4b6cbd9a3410387bd45a,1508.0,0.0,0.0,420.0,0.0,0.0,0.0,1.0,0.0,2.0,5.0,3.0,1.0,0,3.0,3.0,2003.0,0.0,3.0,3.6,1,1,4.0,2015.0,0,0,0,1,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990760,2f9fbea48883c2f530f384e5bc69a9268e6de643,1611.0,0.0,0.0,400.0,35.0,0.0,0.0,1.0,0.0,2.0,6.0,3.0,0.0,0,3.0,3.0,2003.0,0.0,4.0,3.6,1,1,4.0,2015.0,0,0,0,1,0,1,1,0,0,0,0
990761,f4754d6d14db17406de498e110a08893241305d6,2168.0,0.0,0.0,484.0,48.0,0.0,0.0,1.0,0.0,2.0,5.0,3.0,1.0,0,3.0,3.0,1979.0,0.0,4.0,3.6,1,1,4.0,2015.0,0,0,0,1,1,0,0,0,0,0,0
990762,0b85ebef5f4d83efb420ae780c2c8d82d0574771,1723.0,0.0,0.0,460.0,76.0,0.0,0.0,1.0,0.0,2.0,6.0,3.0,1.0,0,3.0,3.0,1983.0,0.0,4.0,3.6,1,1,4.0,2015.0,0,0,0,1,1,0,0,0,0,0,0
990763,c0fc5ae680322e79c8e80abeb4015319fa0c9de6,576.0,576.0,0.0,486.0,0.0,0.0,0.0,2.0,1.0,2.0,5.0,3.0,1.0,0,3.0,3.0,1979.0,0.0,4.0,3.6,1,1,4.0,2015.0,0,0,0,1,0,1,1,0,0,0,0
990764,3db28413f364c8863957f222d3822cdae477ddeb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,4.0,2.0,0.0,0,3.0,3.0,1935.0,0.0,4.0,3.3,0,0,4.0,2015.0,0,1,0,0,0,0,0,1,0,0,0

## Cleaning all the files

In [1]:
df15 = clean_df(BUILDING_DETAILS_2015)

NameError: name 'clean_df' is not defined

In [ ]:
df16 = clean_df(BUILDING_DETAILS_2016)
df17 = clean_df(BUILDING_DETAILS_2017)
df18 = clean_df(BUILDING_DETAILS_2018)
df19 = clean_df(BUILDING_DETAILS_2019)

In [ ]:
df